swagger: '2.0'
info:
  version: '1.0'
  title: "sorrentino-luglio-mondiali"
  description: Servizio di informazioni sul mondiale di calcio
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: sorrentino-luglio-mondiali.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /teams:
    get:
      description: |
        ritorna i dati del team richiesto es. /getTeam?id=55 ritorna i dati del team con id=55 
      operationId: getTeam
      parameters:
        - name: id
          in: query
          description: id del team che stiamo cercando
          required: false
          type: integer
      responses:
        200:
          description: area response
          schema:
            type: string
        400:
          description: unexpected error
    post:
      description: | 
        crea un nuovo team
      summary: aggiungere team
      parameters:
        - name: Team
          in: query
          description: add a team
          required: true
          type: string
      produces: 
        - appication/json 
      responses:
        200:
          description: risposta
          schema:
            type: string
        400:
          description: unexpected error
        


definitions:
  Team:
    type: object
    properties:
      id:
        type: integer
        description: id team
      name:
        type: string
        description: name team
      is_still_in:
        type: boolean
        description: se true la squadra è ancora in corso per la vittoria, se false è uscita dal mondiale    
      matches:
        type: array
        description: partite